version: '3'

services:
        dbos:
         image: mysql:5.7
         volumes:
           - mysql_storage_new:/var/lib/mysql
         restart: always
         environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_USER: anushka
            MYSQL_PASSWORD: anushka
            MYSQL_DATABASE: mydb
        wordpessos:  
         image: wordpress:5.1.1-php7.3-apache
         restart: always
         depends_on:
            - dbos
         ports:
            - 8089:80
         environment:
            WORDPRESS_DB_HOST: dbos
            WORDPRESS_DB_USER: anushka
            WORDPRESS_DB_PASSWORD: anushka
            WORDPRESS_DB_NAME: mydb
         volumes:
            - wp_storage_new:/var/www/html
volumes:
   wp_storage_new:
   mysql_storage_new:

